# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(400, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        SettingsDialog.setMinimumSize(QtCore.QSize(400, 338))
        SettingsDialog.setMaximumSize(QtCore.QSize(400, 338))
        SettingsDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        SettingsDialog.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.node_settings_tab = QtWidgets.QWidget()
        self.node_settings_tab.setObjectName("node_settings_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.node_settings_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.node_host_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.node_host_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.node_host_edit.setObjectName("node_host_edit")
        self.gridLayout.addWidget(self.node_host_edit, 0, 1, 1, 1)
        self.node_host_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.node_host_label.setObjectName("node_host_label")
        self.gridLayout.addWidget(self.node_host_label, 0, 2, 1, 1)
        self.node_port_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.node_port_label.setObjectName("node_port_label")
        self.gridLayout.addWidget(self.node_port_label, 1, 2, 1, 1)
        self.node_fcp_port_edit = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.node_fcp_port_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.node_fcp_port_edit.setMinimum(1025)
        self.node_fcp_port_edit.setMaximum(65535)
        self.node_fcp_port_edit.setProperty("value", 9481)
        self.node_fcp_port_edit.setObjectName("node_fcp_port_edit")
        self.gridLayout.addWidget(self.node_fcp_port_edit, 1, 1, 1, 1)
        self.testResultsEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.testResultsEdit.setObjectName("testResultsEdit")
        self.gridLayout.addWidget(self.testResultsEdit, 4, 1, 1, 1)
        self.testSettingsButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.testSettingsButton.setObjectName("testSettingsButton")
        self.gridLayout.addWidget(self.testSettingsButton, 4, 2, 1, 1)
        self.node_http_port_edit = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.node_http_port_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.node_http_port_edit.setMinimum(1025)
        self.node_http_port_edit.setMaximum(65535)
        self.node_http_port_edit.setProperty("value", 8888)
        self.node_http_port_edit.setObjectName("node_http_port_edit")
        self.gridLayout.addWidget(self.node_http_port_edit, 2, 1, 1, 1)
        self.fproxy_port_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fproxy_port_label.setObjectName("fproxy_port_label")
        self.gridLayout.addWidget(self.fproxy_port_label, 2, 2, 1, 1)
        self.node_use_https = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.node_use_https.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.node_use_https.setText("")
        self.node_use_https.setObjectName("node_use_https")
        self.gridLayout.addWidget(self.node_use_https, 3, 1, 1, 1)
        self.node_use_https_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.node_use_https_label.setObjectName("node_use_https_label")
        self.gridLayout.addWidget(self.node_use_https_label, 3, 2, 1, 1)
        self.tabWidget.addTab(self.node_settings_tab, "")
        self.http_settings_tab = QtWidgets.QWidget()
        self.http_settings_tab.setObjectName("http_settings_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.http_settings_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 381, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.proxy_host_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.proxy_host_edit.setText("")
        self.proxy_host_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.proxy_host_edit.setObjectName("proxy_host_edit")
        self.gridLayout_2.addWidget(self.proxy_host_edit, 0, 1, 1, 1)
        self.proxy_host_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.proxy_host_label.setObjectName("proxy_host_label")
        self.gridLayout_2.addWidget(self.proxy_host_label, 0, 2, 1, 1)
        self.proxy_port_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.proxy_port_label.setObjectName("proxy_port_label")
        self.gridLayout_2.addWidget(self.proxy_port_label, 1, 2, 1, 1)
        self.proxy_port_edit = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.proxy_port_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.proxy_port_edit.setMinimum(1025)
        self.proxy_port_edit.setMaximum(65535)
        self.proxy_port_edit.setProperty("value", 8118)
        self.proxy_port_edit.setObjectName("proxy_port_edit")
        self.gridLayout_2.addWidget(self.proxy_port_edit, 1, 1, 1, 1)
        self.tabWidget.addTab(self.http_settings_tab, "")
        self.warren_settings_tab = QtWidgets.QWidget()
        self.warren_settings_tab.setObjectName("warren_settings_tab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.warren_settings_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 371, 181))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.file_key_type_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.file_key_type_label.setObjectName("file_key_type_label")
        self.gridLayout_3.addWidget(self.file_key_type_label, 0, 0, 1, 1)
        self.pastebin_key_type_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.pastebin_key_type_label.setObjectName("pastebin_key_type_label")
        self.gridLayout_3.addWidget(self.pastebin_key_type_label, 1, 0, 1, 1)
        self.file_key_type_box = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.file_key_type_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.file_key_type_box.setObjectName("file_key_type_box")
        self.gridLayout_3.addWidget(self.file_key_type_box, 0, 1, 1, 1)
        self.pastebin_key_type_box = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.pastebin_key_type_box.setObjectName("pastebin_key_type_box")
        self.gridLayout_3.addWidget(self.pastebin_key_type_box, 1, 1, 1, 1)
        self.browser_command_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.browser_command_label.setObjectName("browser_command_label")
        self.gridLayout_3.addWidget(self.browser_command_label, 2, 0, 1, 1)
        self.browser_command = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.browser_command.setObjectName("browser_command")
        self.gridLayout_3.addWidget(self.browser_command, 2, 1, 1, 1)
        self.max_clipboard_keys_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.max_clipboard_keys_label.setObjectName("max_clipboard_keys_label")
        self.gridLayout_3.addWidget(self.max_clipboard_keys_label, 3, 0, 1, 1)
        self.max_clipboard_keys = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.max_clipboard_keys.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.max_clipboard_keys.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_clipboard_keys.setMinimum(1)
        self.max_clipboard_keys.setProperty("value", 5)
        self.max_clipboard_keys.setObjectName("max_clipboard_keys")
        self.gridLayout_3.addWidget(self.max_clipboard_keys, 3, 1, 1, 1)
        self.start_with_on_top_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.start_with_on_top_label.setObjectName("start_with_on_top_label")
        self.gridLayout_3.addWidget(self.start_with_on_top_label, 4, 0, 1, 1)
        self.start_with_on_top = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.start_with_on_top.setText("")
        self.start_with_on_top.setObjectName("start_with_on_top")
        self.gridLayout_3.addWidget(self.start_with_on_top, 4, 1, 1, 1)
        self.tabWidget.addTab(self.warren_settings_tab, "")

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.node_host_edit.setText(_translate("SettingsDialog", "127.0.0.1"))
        self.node_host_label.setText(_translate("SettingsDialog", "Host"))
        self.node_port_label.setText(_translate("SettingsDialog", "FCP Port"))
        self.testSettingsButton.setText(_translate("SettingsDialog", "Test Settings"))
        self.fproxy_port_label.setText(_translate("SettingsDialog", "Fproxy Port"))
        self.node_use_https_label.setText(_translate("SettingsDialog", "Fproxy SSL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.node_settings_tab), _translate("SettingsDialog", "Node"))
        self.proxy_host_label.setText(_translate("SettingsDialog", "Proxy Host"))
        self.proxy_port_label.setText(_translate("SettingsDialog", "Proxy Port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.http_settings_tab), _translate("SettingsDialog", "HTTP"))
        self.file_key_type_label.setText(_translate("SettingsDialog", "Insert files with this keytype"))
        self.pastebin_key_type_label.setText(_translate("SettingsDialog", "Insert Pastebin with this keytype"))
        self.browser_command_label.setText(_translate("SettingsDialog", "Browser command\n"
"(empty for system default)"))
        self.max_clipboard_keys_label.setText(_translate("SettingsDialog", "Max freenet keys in menu"))
        self.start_with_on_top_label.setText(_translate("SettingsDialog", "Start with \'Keep on top\' active"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.warren_settings_tab), _translate("SettingsDialog", "Warren"))

